optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  weight_decay: 1e-4
  momentum: 0.9
  
use_lr_scheduler: True

lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [90,130]
  gamma: 0.1
